### ISSUE TITLE
apply a theme to change bootstrap's default colors

### ISSUE THREAD

**Issue by thatbudakguy** [pod4lib/aggregator#459]
right now the site applies bootstrap "dark" styles in a few places, but not in a broad or careful way, which has generated some UI problems (see #456 and #443).

the "vanilla" bootstrap elements, like the primary color for buttons, also very obviously show that the site is "default bootstrap" and hasn't been customized.

most likely we'd want to override all of [bootstrap's top-level "theme colors"](https://getbootstrap.com/docs/5.1/customize/color/#theme-colors) so that they play well together and have an overall sense of identity. here are the defaults:
```yaml
- name: primary
  hex: "#0d6efd"
- name: secondary
  hex: "#6c757d"
- name: success
  hex: "#28a745"
- name: danger
  hex: "#dc3545"
- name: warning
  hex: "#ffc107"
- name: info
  hex: "#17a2b8"
- name: light
  hex: "#f8f9fa"
- name: dark
  hex: "#343a40"
```

we might also want to make an overarching decision about using the "dark versions" of components, like the dark navbar.
